### ISSUE TITLE
setMaxVisibleItems seems to have no effect

### ISSUE THREAD

**Issue by fernnando** [Azoft/CarouselLayoutManager#76]
I'm facing an issue with setting max visible items to carousel, setting the max number to layout manager seems to have no effect at all, it keeps showing 2 items on both sides.

    CarouselLayoutManager layoutManager = new CarouselLayoutManager(CarouselLayoutManager.HORIZONTAL, true); 
    layoutManager.setMaxVisibleItems(1);
    layoutManager.setPostLayoutListener(new CarouselZoomPostLayoutListener());
        
    binding.rvCarousel.setLayoutManager(layoutManager);
    binding.rvCarousel.setHasFixedSize(true);

Am i doing anything wrong here?

**Comment by mig35** [comment]
Hi @fernnando!

Thanks for your report. I do not see any problem.
As it is said in the docs: "Basically during scrolling there can be more visible items (+1 item on each side), but in idle state this is the only reached maximum". So if you see 2 items on each side in the idle state (while you set your maximum to 1), then this is a bug. Otherwise it is not.

If you still think that this is a bug, then post a gif with bug, your device info and layouts (recyclerview and adapter) that you are using.

Thanks.

**Comment by fernnando** [comment]
Thanks for aswering @mig35 ;)

Actually its showing 2 items on both sides, even in iddle state. Last night i downloaded your sample project and there setMaxVisibleItems is working fine, probably there's something in my project im messing up. I'll check better my code, if the problem is related to any bug i'll posting here.

Thanks!

**Comment by teshlya** [comment]
fernnando, I have the same problem. How did you decide it?

**Comment by jpvs0101** [comment]
Sure it has. To check that just put a container as Match Parent in
landscape mode with max items 2.

Now change it to 6.
You can see difference!
On 13-Aug-2018 11:13 pm, "teshlya" <notifications@github.com> wrote:

fernnando, I have the same problem. How did you decide it?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azoft/CarouselLayoutManager/issues/76#issuecomment-412603056>,
or mute the thread

**Comment by Gadiq** [comment]
On idle experiencing same issue with maxVal = 1 it shows 2 items left and right.

**Comment by Morteza-Rastgoo** [comment]
@mig35 in the sample if you remove the background color and scroll the items, you'll see there is 2 items loading even if you put `layoutManager.setMaxVisibleItems(1);` 

<img width="613" alt="Screen Shot 2019-07-30 at 4 20 54 PM" src="https://user-images.githubusercontent.com/5219339/62126922-09e90880-b2e6-11e9-902f-33a759b45cec.png">
