### ISSUE TITLE
Increase child height and width

### ISSUE THREAD

**Issue by ronmeroz** [Azoft/CarouselLayoutManager#80]
Hey, I want to increase the size of a child (without changing the scroll or the size of the card that in the middle - only make the child higher).
If anyone knows how to do it, I will thank him very much.

**Comment by mig35** [comment]
Hi @ronmeroz 

I don't get your issue, can you provide any image or better explanation?
Also the zooming size and transition are controlled in https://github.com/Azoft/CarouselLayoutManager/blob/master/CarouselLayoutManager/carousel/src/main/java/com/azoft/carousellayoutmanager/CarouselZoomPostLayoutListener.java

**Comment by ronmeroz** [comment]
![74defe35-8ba3-40d7-b53c-6de0c4902359](https://user-images.githubusercontent.com/39269393/42450716-c4236a26-838d-11e8-90f0-fe8f7c4f7422.jpg)

@mig35 I want the child to be in the size like the purple line in the picture.

**Comment by mig35** [comment]
@ronmeroz 
As I can see you are editing my sample app and I used fixed sized RecyclerView there. So you should edit it to have any size except wrap_content because it is not supported now.
I'm sure that if you give any background to the RecyclerView it will not be full screen. So just check the height argument there.
